# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'allotattoo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for allotattoo
pod 'Firebase/Auth'
pod 'RESideMenu', '~> 4.0.7'
pod 'Firebase'
pod 'MBProgressHUD', '~> 0.9'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'DBCamera', '~> 2.4'
pod 'SDWebImage', '~>3.7'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Invites'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'JSONModel', '~> 1.2'
pod 'IQAudioRecorderController'
pod 'JSQMessagesViewController'
pod 'ProgressHUD'
pod 'Reachability'
pod 'RNGridMenu'
pod 'CLGCommentInputViewController', '~> 1.0'
pod 'MGInstagram', '~> 0.1'
pod 'AAShareBubbles'
pod 'MaterialControls', '~> 1.1.0'
end
